Loonie-Toons/Re-Edited

Modules/GuessManager.cs
Modules/Utils.cs

Fixed a bug where guessers would display the id of the players in the middle of the game

Fix Guessers

---

Modules/GameOptionsSender/PlayerGameOptionsSender.cs
Modules/OptionHolder.cs
Resources/String.csv

I accidentally deleted text in csv "TeleportedInRndVentByDisperser"
And add new option for Lighter, since for weak devices a high vision causes lags

Option: Lighter Vision and Fix csv "TeleportedInRndVentByDisperser"

---

Patches/PlayerContorolPatch.cs
Roles/Impostor/Camouflager.cs

Fix a bug when Camouflager dies, camouflage disappears only at the beginning of the meeting

Fix Camouflager

---

Modules/GameState.cs
Resources/String.csv
Roles/Impostor/Disperser.cs

Fixed an issue where the Transporter and Disperser teleported players who were climbing stairs and getting stuck in textures
Also added teleportation error message

Error Teleport & Fix Teleport

---

Modules/ExtendedPlayerControl.cs
Modules/GameOptionsSender/PlayerGameOptionsSender.cs
Modules/OptionHolder.cs
Patches/ShipStatusPatch.cs

Also other minor fixes and changes

Fix Neutrals Can Sabotage

---

Patches/ChatCommandPatch.cs

Fix "/up" command when choosing a role at the beginning of the game was a completely different role

Fix command "/up"

---

Modules/Utils.cs
Patches/MeetingHudPatch.cs
Roles/Crewmate/Tracker.cs

Add for Tracker last room in meeting under nickname target

---

Modules/OptionHolder.cs
Resources/String.csv

Move vanilla roles option

---

Patches/PlayerContorolPatch.cs
Roles/Crewmate/Marshall.cs

This option is non existent. Is this something upcoming or can it be removed?

fix marshall OptionItem

---

Modules/GuessManager.cs
Modules/ModUpdater.cs
Patches/CredentialsPatch.cs
Resources/String.csv
TOHE.csproj
main.cs

Mod support for AU v2023.6.13

---

Roles/Impostor/QuickShooter.cs

Quick shooter fix

---

Roles/Impostor/Witch.cs

Witch dictionary fix

---

Modules/CustomRolesHelper.cs
Modules/ExtendedPlayerControl.cs
Modules/OptionHolder.cs
Modules/RPC.cs
Modules/Utils.cs
Patches/MeetingHudPatch.cs
Patches/PlayerContorolPatch.cs
Patches/onGameStartedPatch.cs
Resources/String.csv
Roles/Neutral/Seeker.cs
main.cs

1. New role: Seeker
2. Shaman coven fix
3. Add setting for godfather
#237

Added Seeker & Some fix (coded by ryuk)

---

Modules/CustomRolesHelper.cs
main.cs

Replaced the inconvenient use of if with a switch statement
Since many players use multiple add-ons per player, this will slightly improve the loading of the game (maybe a lot, but I'm not sure)

Improve "CheckAddonConfilct" function

---

Modules/Utils.cs
Patches/PlayerContorolPatch.cs
Patches/onGameStartedPatch.cs
Resources/String.csv
main.cs

Add guard animation to notify the killer that burst is done.
Prevent killer from reporting burst's body so it cannot dogge.

Improve burst addon

---

Modules/Utils.cs
Patches/MeetingHudPatch.cs
Roles/Crewmate/Crusader.cs

Ignore these commits because I accidentally added them to the TOHE branch, lol

Fix Doomsayer ID

---

Modules/GuessManager.cs
Modules/Utils.cs
Patches/ExilePatch.cs
Patches/MeetingHudPatch.cs

Remove my trash codes while fixing guesser addon
Also Fix exile patch...

Remove my trash codes on Guesser addon

---

Patches/MeetingHudPatch.cs

https://discord.com/channels/1094344790910455908/1142402868834476142
Should check seer.subrole...

Simple Fix for Guesser addon

---

Modules/Utils.cs
Patches/ChatCommandPatch.cs

I built my Moderators.txt like this and it wouldnt work:
example#3360,Niko233
example#3747,Niko233
Apparently contains check won't work for string[]...
Redo this like eaclist check.
Also I noticed that /up will broadcast messages to everyone. Improved this.

Fix Moderators Check and /up

---

main.cs

Role Summary Default On

---

Patches/SabotageSystemPatch.cs
Patches/ShipStatusPatch.cs

During the game, I noticed bugs with camouflage, so I returned the code

Fix Camouflague

---

GameMode/SoloKombatManager.cs
Modules/GameState.cs
Modules/Utils.cs
Patches/PlayerControlPatch.cs
Patches/RandomSpawnPatch.cs
Roles/Impostor/Assassin.cs
Roles/Impostor/Disperser.cs
Roles/Impostor/Twister.cs
Roles/Neutral/Pelican.cs
main.cs

Maybe this will fix the teleportation issues, but I'm not sure if it will help

Code Rework For Teleport

---

Patches/ControlPatch.cs
Patches/DisconnectPenaltyPatch.cs

Prevent shift force start the game while chatting
Check Invalid color player on force start so room won't get boomed.
"Innersloth already did most of the work..."

Improve force start

---

Patches/ChatCommandPatch.cs

might need testing in all languages

fix guessing for similar names (example occultist, cultist)

---

Modules/Camouflague.cs
Modules/Utils.cs
Patches/PlayerControlPatch.cs

In the future, I will probably make some more improvements

Improve NotifyRoles (for target)

---

Resources/NewString.json

Fixed an issue where Oracle did not correspond to the source code, resulting in a language error

Fixing Language Errors in Oracle

---

Modules/TemplateManager.cs
Modules/Translator.cs
Patches/PlayerControlPatch.cs
Roles/AddOns/Crewmate/Workhorse.cs

Read more here:
https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1825.md

CA1825: Avoid zero-length array allocations

---

Modules/CustomRolesHelper.cs

If God is allowed to get Guesser, that...

Making add-ons unavailable to some Roles

---

Patches/PlayerControlPatch.cs

Perhaps constant checking of RoleExist() causes lags for the Host, so this will be removed temporarily

Remowe RoleExist() In FixedUpdatePatch

---

Modules/MafiaRevengeManager.cs
Modules/NecromancerRevengeManager.cs
Modules/RPC.cs
Modules/RetributionistRevengeManager.cs
Modules/Utils.cs
Patches/MeetingHudPatch.cs
Patches/PlayerControlPatch.cs
Resources/Data/en.json
Resources/Data/zh-CN.json
Roles/Crewmate/Admirer.cs
Roles/Crewmate/Judge.cs
Roles/Double/Mini.cs
Roles/Impostor/Councillor.cs

Add sync mini age rpc
Anti guess for mini before age 18
Make update age effictive.

RPC & Anti Guess

---

Patches/AnnouncementPatch.cs
main.cs

Added an announcement for version 3.1.0 so that after a long time you don’t have to look for all the changes and fixes in this version
Naturally, these changes are not final

Add Announcement For Version 3.1.0

---

Modules/RPC.cs

Fix Swapper RPC kicking clients

---

Modules/ChatManager.cs
Modules/GuessManager.cs
Roles/Crewmate/Judge.cs
Roles/Crewmate/ParityCop.cs
Roles/Crewmate/Swapper.cs
Roles/Impostor/Councillor.cs
Roles/Neutral/Pirate.cs

1. Removed conflicitng commands from guess manager, judge, councillor and swapper.
2. Added NewHideMsg to Guessing roles, judge, councillor, swapper, pirate and paritycop

fix conflicting commands and Added New spam mechanism to various roles
